//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp50
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public int final_price_id { get; set; }
        public string identity { get; set; }
    
        public virtual final_price final_price { get; set; }
    }
}
